name = "ConfigurationsEnv"
uuid = "4a543033-a920-4921-b9ec-d69f25e1cf2a"
authors = ["Stephan Sahm <stephan.sahm@jolin.io> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
